### ISSUE TITLE
Add run instructions to the README.md

### ISSUE THREAD

**Issue by joaompinto** [TVScoundrel/mmo-phaser-es6#1]
Because I have no experience with nodejs I was unable to launch the server.js, could you please add some instructions to thre README ?

Thanks

**Comment by TVScoundrel** [comment]
Hi @joaompinto,

I had only started this project as an exercise for myself to get used to Phaser in an ES6 context.
This is a refactor of another project: https://github.com/Jerenaux/basic-mmo-phaser

That being said however, it is nice that people would want to start using this for their own projects, so when I get time today I will add some instructions.

Cheers!
Tom

**Comment by TVScoundrel** [comment]
The README has been updated with some basic instructions.

**Comment by joaompinto** [comment]
I actually came to your repo from a comment on some article related to Jerome's repo, mentioning this repo had some code restrucuting. I tested with your instructions and was able to run. 

Thanks.
